import type {
  ActionDefinition,
  ActionHandlerName,
  ActionId,
  ModuleCode,
  PermissionCode,
  Phase,
} from "./types";

interface ActionSeed {
  id: ActionId;
  label: string;
  moduleCode: ModuleCode;
  permission: PermissionCode;
  sideEffect: string;
  tone?: "primary" | "secondary" | "danger";
  requiresConfirmation?: boolean;
  phase: Phase;
  preconditions?: string[];
}

const handlerByModule: Record<ModuleCode, ActionHandlerName> = {
  SYS: "DashboardService.handleAction",
  DATA: "DataPackageService.handleAction",
  RES: "ResourceService.handleAction",
  PARTY: "PartyService.handleAction",
  QUAL: "QualityService.handleAction",
  DU: "ShuyuanService.handleAction",
  UTIL: "UtilityService.handleAction",
  MDS: "MDDShapService.handleAction",
  ALLOC: "AllocationService.handleAction",
  CONS: "ConstraintService.handleAction",
  REP: "ReportService.handleAction",
  PARAM: "ParameterService.handleAction",
  USER: "UserService.handleAction",
  AUD: "AuditService.handleAction",
};

const objectTypeByModule: Record<ModuleCode, string> = {
  SYS: "dashboard_workspace",
  DATA: "data_package",
  RES: "data_resource",
  PARTY: "party",
  QUAL: "quality_assessment",
  DU: "shuyuan_metering",
  UTIL: "utility_record",
  MDS: "md_dshap_task",
  ALLOC: "allocation_scenario",
  CONS: "contract_constraint",
  REP: "report_record",
  PARAM: "system_parameter",
  USER: "user_account_p1",
  AUD: "audit_log",
};

const permissionPreconditions: Record<PermissionCode, string[]> = {
  VIEW: ["当前页面可访问"],
  CREATE: ["项目未锁定", "必要输入已通过校验"],
  UPDATE: ["项目未锁定", "存在可编辑版本"],
  DELETE_DISABLE: ["项目未锁定", "确认逻辑停用影响"],
  CALCULATE: ["前置快照存在", "项目未锁定", "参数版本有效"],
  CONFIRM: ["模拟结果已生成", "已阅读模拟参考边界"],
  EXPORT: ["存在可导出结果", "已确认字段范围和模拟参考边界"],
};

function defineAction(seed: ActionSeed): ActionDefinition {
  return {
    ...seed,
    handlerName: handlerByModule[seed.moduleCode],
    preconditions: seed.preconditions ?? permissionPreconditions[seed.permission],
    audit: {
      operationType: seed.permission,
      objectType: objectTypeByModule[seed.moduleCode],
      writes:
        seed.permission === "VIEW"
          ? ["read_audit_trace"]
          : ["input_snapshot", "parameter_snapshot", "output_snapshot", "audit_log"],
    },
  };
}

export const actionRegistry = {
  "SYS-002": defineAction({
    id: "SYS-002",
    label: "选择演示数据",
    moduleCode: "SYS",
    permission: "CREATE",
    sideEffect: "创建项目、数据包和输入快照",
    tone: "primary",
    phase: "P0",
  }),
  "SYS-004": defineAction({
    id: "SYS-004",
    label: "执行完整链路计算",
    moduleCode: "SYS",
    permission: "CALCULATE",
    sideEffect: "按完整链路写入阶段快照和审计日志",
    tone: "primary",
    requiresConfirmation: true,
    phase: "P0",
  }),
  "SYS-005": defineAction({
    id: "SYS-005",
    label: "查看风险边界",
    moduleCode: "SYS",
    permission: "VIEW",
    sideEffect: "只读展示风险提示",
    phase: "P0",
  }),
  "DATA-002": defineAction({
    id: "DATA-002",
    label: "选择演示数据",
    moduleCode: "DATA",
    permission: "CREATE",
    sideEffect: "生成演示数据包和输入快照",
    tone: "primary",
    phase: "P0",
  }),
  "DATA-003": defineAction({
    id: "DATA-003",
    label: "上传 JSON",
    moduleCode: "DATA",
    permission: "CREATE",
    sideEffect: "创建上传校验结果和输入快照",
    tone: "primary",
    phase: "P0",
  }),
  "DATA-007": defineAction({
    id: "DATA-007",
    label: "预览安全摘要",
    moduleCode: "DATA",
    permission: "VIEW",
    sideEffect: "读取校验后的安全字段摘要",
    phase: "P0",
  }),
  "DATA-008": defineAction({
    id: "DATA-008",
    label: "查看失败详情",
    moduleCode: "DATA",
    permission: "VIEW",
    sideEffect: "读取校验失败字段和修复建议",
    phase: "P0",
  }),
  "DATA-009": defineAction({
    id: "DATA-009",
    label: "停用数据包",
    moduleCode: "DATA",
    permission: "DELETE_DISABLE",
    sideEffect: "逻辑停用数据包并写入审计",
    tone: "danger",
    requiresConfirmation: true,
    phase: "P0",
  }),
  "RES-002": defineAction({
    id: "RES-002",
    label: "查看资源详情",
    moduleCode: "RES",
    permission: "VIEW",
    sideEffect: "读取资源字段和基础统计",
    phase: "P0",
  }),
  "RES-005": defineAction({
    id: "RES-005",
    label: "绑定数据源主体",
    moduleCode: "RES",
    permission: "UPDATE",
    sideEffect: "写入资源与数据源主体关系",
    tone: "primary",
    phase: "P0",
  }),
  "RES-007": defineAction({
    id: "RES-007",
    label: "导出资源摘要",
    moduleCode: "RES",
    permission: "EXPORT",
    sideEffect: "生成资源摘要导出记录和校验和",
    phase: "P0",
  }),
  "PARTY-002": defineAction({
    id: "PARTY-002",
    label: "新增参与方",
    moduleCode: "PARTY",
    permission: "CREATE",
    sideEffect: "创建参与方记录",
    tone: "primary",
    phase: "P0",
  }),
  "PARTY-003": defineAction({
    id: "PARTY-003",
    label: "编辑参与方",
    moduleCode: "PARTY",
    permission: "UPDATE",
    sideEffect: "更新参与方并写入变更审计",
    phase: "P0",
  }),
  "PARTY-005": defineAction({
    id: "PARTY-005",
    label: "停用参与方",
    moduleCode: "PARTY",
    permission: "DELETE_DISABLE",
    sideEffect: "逻辑停用参与方并保留历史",
    tone: "danger",
    requiresConfirmation: true,
    phase: "P0",
  }),
  "PARTY-006": defineAction({
    id: "PARTY-006",
    label: "关联资源",
    moduleCode: "PARTY",
    permission: "UPDATE",
    sideEffect: "写入参与方与数据资源关系",
    phase: "P0",
  }),
  "PARTY-008": defineAction({
    id: "PARTY-008",
    label: "查看贡献摘要",
    moduleCode: "PARTY",
    permission: "VIEW",
    sideEffect: "读取贡献、效用和权重摘要",
    phase: "P0",
  }),
  "QUAL-002": defineAction({
    id: "QUAL-002",
    label: "保存质量权重",
    moduleCode: "QUAL",
    permission: "UPDATE",
    sideEffect: "创建质量参数版本",
    requiresConfirmation: true,
    phase: "P0",
  }),
  "QUAL-003": defineAction({
    id: "QUAL-003",
    label: "运行质量评估",
    moduleCode: "QUAL",
    permission: "CALCULATE",
    sideEffect: "写入质量评估、详情和快照",
    tone: "primary",
    requiresConfirmation: true,
    phase: "P0",
  }),
  "QUAL-006": defineAction({
    id: "QUAL-006",
    label: "重算质量评估",
    moduleCode: "QUAL",
    permission: "CALCULATE",
    sideEffect: "创建新的评估版本，不覆盖历史",
    requiresConfirmation: true,
    phase: "P0",
  }),
  "QUAL-009": defineAction({
    id: "QUAL-009",
    label: "查看评估详情",
    moduleCode: "QUAL",
    permission: "VIEW",
    sideEffect: "只读展示质量证据和版本",
    phase: "P0",
  }),
  "DU-002": defineAction({
    id: "DU-002",
    label: "保存计量参数",
    moduleCode: "DU",
    permission: "UPDATE",
    sideEffect: "写入基础单价、调用次数和系数输入",
    requiresConfirmation: true,
    phase: "P0",
  }),
  "DU-003": defineAction({
    id: "DU-003",
    label: "执行数元计量",
    moduleCode: "DU",
    permission: "CALCULATE",
    sideEffect: "写入计量主表、详情和输出快照",
    tone: "primary",
    requiresConfirmation: true,
    phase: "P0",
  }),
  "DU-009": defineAction({
    id: "DU-009",
    label: "查看计量公式",
    moduleCode: "DU",
    permission: "VIEW",
    sideEffect: "只读展示公式和版本",
    phase: "P0",
  }),
  "DU-010": defineAction({
    id: "DU-010",
    label: "查看计量明细",
    moduleCode: "DU",
    permission: "VIEW",
    sideEffect: "读取资源、参与方和项目计量明细",
    phase: "P0",
  }),
  "UTIL-001": defineAction({
    id: "UTIL-001",
    label: "保存贡献因子",
    moduleCode: "UTIL",
    permission: "UPDATE",
    sideEffect: "写入贡献与效用参数快照",
    requiresConfirmation: true,
    phase: "P0",
  }),
  "UTIL-006": defineAction({
    id: "UTIL-006",
    label: "计算贡献度",
    moduleCode: "UTIL",
    permission: "CALCULATE",
    sideEffect: "写入贡献记录",
    tone: "primary",
    requiresConfirmation: true,
    phase: "P0",
  }),
  "UTIL-007": defineAction({
    id: "UTIL-007",
    label: "保存效用函数",
    moduleCode: "UTIL",
    permission: "UPDATE",
    sideEffect: "写入效用函数快照",
    requiresConfirmation: true,
    phase: "P0",
  }),
  "UTIL-008": defineAction({
    id: "UTIL-008",
    label: "计算效用值",
    moduleCode: "UTIL",
    permission: "CALCULATE",
    sideEffect: "写入效用记录和轨迹",
    tone: "primary",
    requiresConfirmation: true,
    phase: "P0",
  }),
  "UTIL-009": defineAction({
    id: "UTIL-009",
    label: "查看效用轨迹",
    moduleCode: "UTIL",
    permission: "VIEW",
    sideEffect: "只读展示输入、公式、输出和任务键",
    phase: "P0",
  }),
  "PARAM-001": defineAction({
    id: "PARAM-001",
    label: "查看参数",
    moduleCode: "PARAM",
    permission: "VIEW",
    sideEffect: "读取当前参数版本",
    phase: "P0",
  }),
  "PARAM-002": defineAction({
    id: "PARAM-002",
    label: "保存参数版本",
    moduleCode: "PARAM",
    permission: "UPDATE",
    sideEffect: "创建参数版本并写入前后值审计",
    requiresConfirmation: true,
    phase: "P0",
  }),
  "PARAM-004": defineAction({
    id: "PARAM-004",
    label: "配置 MD-DShap 默认值",
    moduleCode: "PARAM",
    permission: "UPDATE",
    sideEffect: "保存 MD-DShap 默认参数版本",
    requiresConfirmation: true,
    phase: "P0",
  }),
  "PARAM-008": defineAction({
    id: "PARAM-008",
    label: "保存风险提示文案",
    moduleCode: "PARAM",
    permission: "UPDATE",
    sideEffect: "保存风险文案参数版本",
    requiresConfirmation: true,
    phase: "P0",
  }),
  "MDS-011": defineAction({
    id: "MDS-011",
    label: "启动 MD-DShap",
    moduleCode: "MDS",
    permission: "CALCULATE",
    sideEffect: "写入任务、结果、边际轨迹和算法审计快照",
    tone: "primary",
    requiresConfirmation: true,
    phase: "P0",
  }),
  "MDS-012": defineAction({
    id: "MDS-012",
    label: "查看计算进度",
    moduleCode: "MDS",
    permission: "VIEW",
    sideEffect: "打开计算进度抽屉并记录只读审计",
    phase: "P0",
  }),
  "MDS-013": defineAction({
    id: "MDS-013",
    label: "查看边际贡献明细",
    moduleCode: "MDS",
    permission: "VIEW",
    sideEffect: "打开边际贡献 trace 抽屉",
    phase: "P0",
  }),
  "MDS-014": defineAction({
    id: "MDS-014",
    label: "查看参与方权重",
    moduleCode: "MDS",
    permission: "VIEW",
    sideEffect: "展示权重表并校验权重合计为 1",
    phase: "P0",
  }),
  "MDS-015": defineAction({
    id: "MDS-015",
    label: "查看复杂度优化说明",
    moduleCode: "MDS",
    permission: "VIEW",
    sideEffect: "打开复杂度优化说明弹窗",
    phase: "P0",
  }),
  "MDS-016": defineAction({
    id: "MDS-016",
    label: "重新计算",
    moduleCode: "MDS",
    permission: "CALCULATE",
    sideEffect: "创建新的任务和结果版本，不覆盖历史",
    requiresConfirmation: true,
    phase: "P0",
  }),
  "MDS-017": defineAction({
    id: "MDS-017",
    label: "导出算法结果",
    moduleCode: "MDS",
    permission: "EXPORT",
    sideEffect: "生成算法结果 export_file 和 report_record",
    phase: "P0",
  }),
  "MDS-018": defineAction({
    id: "MDS-018",
    label: "生成算法审计说明",
    moduleCode: "MDS",
    permission: "EXPORT",
    sideEffect: "生成 md_dshap_audit_report mock 记录",
    phase: "P0",
  }),
  "ALLOC-003": defineAction({
    id: "ALLOC-003",
    label: "保存收益输入",
    moduleCode: "ALLOC",
    permission: "UPDATE",
    sideEffect: "保存总收益、优先分配和收益池输入",
    requiresConfirmation: true,
    phase: "P0",
  }),
  "ALLOC-005": defineAction({
    id: "ALLOC-005",
    label: "执行收益分配",
    moduleCode: "ALLOC",
    permission: "CALCULATE",
    sideEffect: "写入分配方案、结果和约束应用轨迹",
    tone: "primary",
    requiresConfirmation: true,
    phase: "P0",
  }),
  "ALLOC-007": defineAction({
    id: "ALLOC-007",
    label: "查看方案对比",
    moduleCode: "ALLOC",
    permission: "VIEW",
    sideEffect: "只读展示约束前后对比",
    phase: "P0",
  }),
  "ALLOC-011": defineAction({
    id: "ALLOC-011",
    label: "锁定参考方案",
    moduleCode: "ALLOC",
    permission: "CONFIRM",
    sideEffect: "确认方案并写入审计",
    tone: "primary",
    requiresConfirmation: true,
    phase: "P0",
  }),
  "ALLOC-013": defineAction({
    id: "ALLOC-013",
    label: "导出分配结果",
    moduleCode: "ALLOC",
    permission: "EXPORT",
    sideEffect: "生成分配结果导出记录",
    phase: "P0",
  }),
  "ALLOC-014": defineAction({
    id: "ALLOC-014",
    label: "复制新版本",
    moduleCode: "ALLOC",
    permission: "CREATE",
    sideEffect: "复制当前方案作为新版本",
    phase: "P0",
  }),
  "ALLOC-015": defineAction({
    id: "ALLOC-015",
    label: "查看四舍五入说明",
    moduleCode: "ALLOC",
    permission: "VIEW",
    sideEffect: "只读展示金额精度和尾差规则",
    phase: "P0",
  }),
  "ALLOC-016": defineAction({
    id: "ALLOC-016",
    label: "查看约束轨迹",
    moduleCode: "ALLOC",
    permission: "VIEW",
    sideEffect: "读取约束应用轨迹",
    phase: "P0",
  }),
  "CONS-002": defineAction({
    id: "CONS-002",
    label: "新增约束",
    moduleCode: "CONS",
    permission: "CREATE",
    sideEffect: "创建合同约束",
    tone: "primary",
    phase: "P0",
  }),
  "CONS-003": defineAction({
    id: "CONS-003",
    label: "编辑约束",
    moduleCode: "CONS",
    permission: "UPDATE",
    sideEffect: "更新约束并写入前后值审计",
    requiresConfirmation: true,
    phase: "P0",
  }),
  "CONS-004": defineAction({
    id: "CONS-004",
    label: "停用约束",
    moduleCode: "CONS",
    permission: "DELETE_DISABLE",
    sideEffect: "逻辑停用约束",
    tone: "danger",
    requiresConfirmation: true,
    phase: "P0",
  }),
  "CONS-011": defineAction({
    id: "CONS-011",
    label: "检查约束结果",
    moduleCode: "CONS",
    permission: "VIEW",
    sideEffect: "读取约束应用结果",
    phase: "P0",
  }),
  "REP-001": defineAction({
    id: "REP-001",
    label: "预览报告",
    moduleCode: "REP",
    permission: "VIEW",
    sideEffect: "读取结果快照形成报告预览",
    phase: "P0",
  }),
  "REP-002": defineAction({
    id: "REP-002",
    label: "导出 Markdown",
    moduleCode: "REP",
    permission: "EXPORT",
    sideEffect: "生成 Markdown 报告、报告记录和校验和",
    phase: "P0",
  }),
  "REP-003": defineAction({
    id: "REP-003",
    label: "导出 CSV",
    moduleCode: "REP",
    permission: "EXPORT",
    sideEffect: "生成 CSV 文件、报告记录和校验和",
    phase: "P0",
  }),
  "REP-004": defineAction({
    id: "REP-004",
    label: "导出 JSON",
    moduleCode: "REP",
    permission: "EXPORT",
    sideEffect: "生成 JSON 文件、报告记录和校验和",
    phase: "P0",
  }),
  "REP-005": defineAction({
    id: "REP-005",
    label: "导出 JSONL",
    moduleCode: "REP",
    permission: "EXPORT",
    sideEffect: "生成审计友好的 JSONL 文件",
    phase: "P0",
  }),
  "REP-006": defineAction({
    id: "REP-006",
    label: "导出确认说明",
    moduleCode: "REP",
    permission: "EXPORT",
    sideEffect: "生成包含模拟边界的确认说明",
    phase: "P0",
  }),
  "REP-009": defineAction({
    id: "REP-009",
    label: "PDF 导出",
    moduleCode: "REP",
    permission: "EXPORT",
    sideEffect: "P1 规划项，P0 不生成 PDF",
    phase: "P1",
  }),
  "USER-001": defineAction({
    id: "USER-001",
    label: "新增用户",
    moduleCode: "USER",
    permission: "CREATE",
    sideEffect: "P1 规划项，未来创建用户",
    phase: "P1",
  }),
  "USER-002": defineAction({
    id: "USER-002",
    label: "编辑用户",
    moduleCode: "USER",
    permission: "UPDATE",
    sideEffect: "P1 规划项，未来更新用户",
    phase: "P1",
  }),
  "USER-007": defineAction({
    id: "USER-007",
    label: "配置角色",
    moduleCode: "USER",
    permission: "UPDATE",
    sideEffect: "P1 规划项，未来写入角色权限",
    phase: "P1",
  }),
  "USER-008": defineAction({
    id: "USER-008",
    label: "查看权限矩阵",
    moduleCode: "USER",
    permission: "VIEW",
    sideEffect: "P1 规划项，当前只读展示",
    phase: "P1",
  }),
  "USER-009": defineAction({
    id: "USER-009",
    label: "重置密码",
    moduleCode: "USER",
    permission: "UPDATE",
    sideEffect: "P1 规划项，P0 不生成重置令牌",
    phase: "P1",
  }),
  "AUD-002": defineAction({
    id: "AUD-002",
    label: "查询审计日志",
    moduleCode: "AUD",
    permission: "VIEW",
    sideEffect: "读取操作、计算和导出日志",
    phase: "P0",
  }),
  "AUD-006": defineAction({
    id: "AUD-006",
    label: "查看快照详情",
    moduleCode: "AUD",
    permission: "VIEW",
    sideEffect: "读取输入、参数、输出和报告快照",
    phase: "P0",
  }),
  "AUD-007": defineAction({
    id: "AUD-007",
    label: "导出审计日志",
    moduleCode: "AUD",
    permission: "EXPORT",
    sideEffect: "生成审计导出文件和报告记录",
    phase: "P0",
  }),
} satisfies Record<ActionId, ActionDefinition>;

export function getActions(actionIds: ActionId[]) {
  return actionIds.map((id) => actionRegistry[id]);
}

export function getActionRegistryIntegrityReport(
  knownHandlers: Set<ActionHandlerName>,
) {
  const missingHandlers = Object.values(actionRegistry)
    .filter((action) => !knownHandlers.has(action.handlerName))
    .map((action) => `${action.id}:${action.handlerName}`);
  const actionsMissingAudit = Object.values(actionRegistry)
    .filter((action) => action.audit.writes.length === 0)
    .map((action) => action.id);
  const actionsMissingPreconditions = Object.values(actionRegistry)
    .filter((action) => action.preconditions.length === 0)
    .map((action) => action.id);

  return {
    missingHandlers,
    actionsMissingAudit,
    actionsMissingPreconditions,
  };
}
