import type { FieldDefinition, RouteFieldMapping } from "./types";

export const engineeringFieldKeys = new Set([
  "project_id",
  "page_id",
  "route_aliases",
  "audit_events",
  "package_id",
  "relation_id",
  "snapshot_id",
  "input_snapshot_id",
  "parameter_snapshot_id",
  "output_snapshot_id",
  "source_snapshot_id",
  "current_package_id",
  "current_algorithm_task_id",
  "current_allocation_id",
  "report_id",
  "checksum",
  "menu_code",
  "module_code",
  "validation_result_id",
  "resource_id",
  "field_id",
  "party_id",
  "assessment_id",
  "detail_id",
  "metering_id",
  "contribution_id",
  "utility_id",
  "utility_function_snapshot_id",
  "trace_id",
  "task_id",
  "result_id",
  "allocation_id",
  "item_id",
  "constraint_id",
  "file_id",
  "parameter_id",
  "parameter_version_id",
  "user_id",
  "role_id",
  "permission_id",
  "log_id",
  "object_id",
]);

export const fieldLabels: Record<string, string> = {
  project_name: "项目名称",
  scenario_name: "场景名称",
  status: "状态",
  current_package: "当前数据包",
  current_algorithm_task: "当前算法任务",
  current_allocation: "当前分配方案",
  recent_report_type: "最近报告类型",
  recent_report_time: "最近报告时间",
  workflow_step: "流程步骤",
  step_status: "步骤状态",
  blocker: "阻塞项",
  next_module: "下一模块",
  next_action: "下一动作",
  last_updated: "更新时间",
  data_boundary: "数据边界",
  simulation_disclaimer: "模拟说明",
  sensitive_data_notice: "敏感数据提示",
  algorithm_boundary: "算法边界",
  contract_boundary: "合同边界",
  report_boundary: "报告边界",
  precondition_name: "前置条件",
  check_result: "检查结果",
  failed_stage: "失败节点",
  run_mode: "运行模式",
  algorithm_mode: "算法模式",
  pipeline_stage: "流水线阶段",
  stage_status: "阶段状态",
  package_name: "数据包名称",
  source_type: "来源类型",
  file_name: "文件名",
  validation_status: "校验状态",
  access_status: "接入状态",
  resource_count: "资源数量",
  party_count: "参与方数量",
  created_at: "创建时间",
  error_field: "错误字段",
  repair_suggestion: "修复建议",
  resource_name: "资源名称",
  modality: "模态",
  field_count: "字段数",
  sample_count: "样本数",
  missing_rate: "缺失率",
  sensitive_field_count: "敏感字段数",
  provider_party: "数据源主体",
  split_ratio: "拆分比例",
  include_in_calculation: "是否进入后续计算",
  party_name: "参与方名称",
  party_type: "参与方类型",
  is_data_provider: "是否数据源主体",
  include_in_md_dshap: "是否进入算法权重池",
  linked_resource_count: "关联资源数",
  contribution_summary: "贡献摘要",
  metric_name: "指标名称",
  metric_weight: "指标权重",
  score: "分数",
  total_score: "总分",
  quality_level: "质量等级",
  quality_factor: "质量因子",
  evidence_summary: "证据摘要",
  low_quality_warning: "低质量预警",
  base_shuyuan_price: "数元基础单价",
  scenario_coefficient: "场景系数",
  quality_coefficient: "质量系数",
  technology_coefficient: "技术系数",
  expert_coefficient: "专家系数",
  development_coefficient: "发展系数",
  call_count: "调用次数",
  metering_amount: "计量金额",
  valid_units: "有效数元数",
  usage_weight: "使用权重",
  coverage_weight: "覆盖权重",
  scarcity_weight: "稀缺权重",
  contribution_score: "贡献分",
  normalized_contribution: "归一化贡献",
  usage_factor: "使用因子",
  scenario_factor: "场景因子",
  utility_value: "效用值",
  participant_set: "参与者集合",
  task_set: "任务集合",
  sample_rounds: "采样轮次",
  epsilon: "收敛阈值",
  task_status: "任务状态",
  participant_weight: "参与者权重",
  normalized_weight: "归一化权重",
  marginal_contribution: "边际贡献",
  total_revenue: "总收益",
  priority_allocation_amount: "优先分配金额",
  data_provider_revenue_pool: "数据源收益池",
  allocation_mode: "分配模式",
  raw_weight: "原始权重",
  pre_constraint_amount: "约束前金额",
  post_constraint_amount: "约束后金额",
  adjustment_reason: "调整原因",
  scenario_status: "方案状态",
  constraint_name: "约束名称",
  constraint_type: "约束类型",
  value_type: "取值类型",
  constraint_value: "约束值",
  priority: "优先级",
  before_amount: "调整前金额",
  after_amount: "调整后金额",
  reason: "原因",
  report_type: "报告类型",
  report_status: "报告状态",
  file_type: "文件类型",
  field_scope: "字段范围",
  generated_at: "生成时间",
  created_by: "创建人",
  download_status: "下载状态",
  p1_pdf_boundary: "PDF 边界",
  parameter_group: "参数组",
  parameter_name: "参数名称",
  parameter_value: "参数值",
  effective_status: "生效状态",
  version_no: "版本号",
  updated_by: "更新人",
  updated_at: "更新时间",
  risk_disclaimer_text: "风险提示文本",
  username: "用户名",
  display_name: "显示名",
  role_name: "角色",
  menu_permission: "菜单权限",
  button_permission: "按钮权限",
  account_status: "账号状态",
  p1_boundary: "P1 边界",
  operation_type: "操作类型",
  object_type: "对象类型",
  operator_id: "操作员",
  module_code_display: "模块显示",
  menu_code_display: "菜单显示",
  failure_reason: "失败原因",
  page_id: "页面编号",
  route_aliases: "兼容路由",
  audit_events: "审计事件",
  project_id: "项目编号",
  current_package_id: "当前数据包编号",
  current_algorithm_task_id: "当前算法任务编号",
  current_allocation_id: "当前分配方案编号",
  package_id: "数据包编号",
  input_snapshot_id: "输入快照编号",
  parameter_snapshot_id: "参数快照编号",
  output_snapshot_id: "输出快照编号",
  source_snapshot_id: "来源快照编号",
  snapshot_id: "快照编号",
  snapshot_type: "快照类型",
  validation_result_id: "校验结果编号",
  detail_json: "校验详情",
  operator: "操作员",
  menu_code: "菜单编码",
  module_code: "模块编码",
  resource_id: "资源编号",
  field_id: "字段编号",
  relation_id: "关系编号",
  is_primary_provider: "是否主数据源",
  party_id: "参与方编号",
  role_snapshot: "角色快照",
  before_value: "变更前值",
  after_value: "变更后值",
  assessment_id: "评估编号",
  detail_id: "明细编号",
  metric_version: "指标版本",
  algorithm_version: "算法版本",
  metering_id: "计量编号",
  contribution_id: "贡献编号",
  utility_id: "效用编号",
  utility_function_snapshot_id: "效用函数快照编号",
  trace_id: "轨迹编号",
  formula_text: "公式文本",
  input_json: "输入 JSON",
  output_json: "输出 JSON",
  task_key: "任务键",
  task_id: "任务编号",
  result_id: "结果编号",
  seed: "随机种子",
  baseline_weight: "baseline 权重",
  weight_diff: "权重差异",
  input_snapshot_json: "输入快照 JSON",
  parameter_snapshot_json: "参数快照 JSON",
  output_snapshot_json: "输出快照 JSON",
  allocation_id: "分配方案编号",
  item_id: "优先项编号",
  weight_task_id: "权重任务编号",
  rounding_note: "尾差说明",
  constraint_id: "约束编号",
  report_id: "报告编号",
  file_id: "文件编号",
  file_path: "文件路径",
  field_scope_json: "字段范围 JSON",
  content_hash: "内容哈希",
  parameter_id: "参数编号",
  parameter_version_id: "参数版本编号",
  parameter_version: "参数版本",
  user_id: "用户编号",
  role_id: "角色编号",
  permission_id: "权限编号",
  permission_code: "权限编码",
  button_code: "按钮编码",
  password_reset_token: "密码重置令牌",
  log_id: "日志编号",
  object_id: "对象编号",
  checksum: "校验和",
};

function businessField(key: string): FieldDefinition {
  return {
    key,
    label: fieldLabels[key] ?? key,
    technical: false,
    visibleInTable: true,
  };
}

function technicalField(key: string): FieldDefinition {
  return {
    key,
    label: fieldLabels[key] ?? key,
    technical: true,
    visibleInTable: false,
  };
}

const businessFields = (keys: string[]) => keys.map(businessField);
const technicalFields = (keys: string[]) => keys.map(technicalField);

export const routeFieldMappings: RouteFieldMapping[] = [
  {
    routePath: "/dashboard/overview",
    menuCode: "NAV_SYS_OVERVIEW",
    moduleCode: "SYS",
    pageName: "首页总览",
    mainTable: "allocation_project",
    tableFields: businessFields([
      "project_name",
      "scenario_name",
      "status",
      "current_package",
      "current_algorithm_task",
      "current_allocation",
      "recent_report_type",
      "recent_report_time",
    ]),
    technicalFields: technicalFields([
      "project_id",
      "current_package_id",
      "current_algorithm_task_id",
      "current_allocation_id",
      "report_id",
      "checksum",
      "menu_code",
      "module_code",
    ]),
  },
  {
    routePath: "/dashboard/process",
    menuCode: "NAV_SYS_PROCESS",
    moduleCode: "SYS",
    pageName: "流程入口",
    mainTable: "snapshot_store",
    tableFields: businessFields([
      "workflow_step",
      "step_status",
      "blocker",
      "next_module",
      "next_action",
      "last_updated",
    ]),
    technicalFields: technicalFields([
      "project_id",
      "snapshot_id",
      "snapshot_type",
      "checksum",
      "menu_code",
      "module_code",
    ]),
  },
  {
    routePath: "/dashboard/risk",
    menuCode: "NAV_SYS_RISK",
    moduleCode: "SYS",
    pageName: "风险提示",
    mainTable: "system_parameter",
    tableFields: businessFields([
      "data_boundary",
      "simulation_disclaimer",
      "sensitive_data_notice",
      "algorithm_boundary",
      "contract_boundary",
      "report_boundary",
    ]),
    technicalFields: technicalFields([
      "parameter_id",
      "parameter_version",
      "updated_by",
      "updated_at",
      "checksum",
    ]),
  },
  {
    routePath: "/dashboard/one-click",
    menuCode: "NAV_SYS_ONE_CLICK",
    moduleCode: "SYS",
    pageName: "一键计算",
    mainTable: "snapshot_store",
    tableFields: businessFields([
      "precondition_name",
      "check_result",
      "failed_stage",
      "run_mode",
      "algorithm_mode",
      "pipeline_stage",
      "stage_status",
    ]),
    technicalFields: technicalFields([
      "project_id",
      "input_snapshot_id",
      "parameter_snapshot_id",
      "output_snapshot_id",
      "log_id",
      "failure_reason",
    ]),
  },
  {
    routePath: "/data/packages",
    menuCode: "NAV_DATA_PACKAGE",
    moduleCode: "DATA",
    pageName: "数据接入管理",
    mainTable: "data_package",
    tableFields: businessFields([
      "package_name",
      "source_type",
      "file_name",
      "validation_status",
      "access_status",
      "resource_count",
      "party_count",
      "created_at",
      "error_field",
      "repair_suggestion",
    ]),
    technicalFields: technicalFields([
      "package_id",
      "input_snapshot_id",
      "validation_result_id",
      "checksum",
      "detail_json",
      "operator",
      "menu_code",
      "module_code",
    ]),
  },
  {
    routePath: "/data/resources",
    menuCode: "NAV_DATA_RESOURCE",
    moduleCode: "RES",
    pageName: "数据资源管理",
    mainTable: "data_resource",
    tableFields: businessFields([
      "resource_name",
      "modality",
      "field_count",
      "sample_count",
      "missing_rate",
      "sensitive_field_count",
      "provider_party",
      "split_ratio",
      "include_in_calculation",
      "status",
    ]),
    technicalFields: technicalFields([
      "resource_id",
      "field_id",
      "relation_id",
      "package_id",
      "project_id",
      "checksum",
      "is_primary_provider",
      "menu_code",
      "module_code",
    ]),
  },
  {
    routePath: "/data/parties",
    menuCode: "NAV_DATA_PARTY",
    moduleCode: "PARTY",
    pageName: "参与方管理",
    mainTable: "party",
    tableFields: businessFields([
      "party_name",
      "party_type",
      "is_data_provider",
      "include_in_md_dshap",
      "linked_resource_count",
      "status",
      "contribution_summary",
    ]),
    technicalFields: technicalFields([
      "party_id",
      "project_id",
      "relation_id",
      "role_snapshot",
      "before_value",
      "after_value",
      "menu_code",
      "module_code",
    ]),
  },
  {
    routePath: "/measure/quality",
    menuCode: "NAV_MEASURE_QUALITY",
    moduleCode: "QUAL",
    pageName: "质量评估管理",
    mainTable: "quality_assessment",
    tableFields: businessFields([
      "metric_name",
      "metric_weight",
      "score",
      "total_score",
      "quality_level",
      "quality_factor",
      "evidence_summary",
      "low_quality_warning",
    ]),
    technicalFields: technicalFields([
      "assessment_id",
      "detail_id",
      "metric_version",
      "parameter_snapshot_id",
      "input_snapshot_id",
      "output_snapshot_id",
      "algorithm_version",
    ]),
  },
  {
    routePath: "/measure/shuyuan",
    menuCode: "NAV_MEASURE_SHUYUAN",
    moduleCode: "DU",
    pageName: "数元计量管理",
    mainTable: "shuyuan_metering",
    tableFields: businessFields([
      "base_shuyuan_price",
      "scenario_coefficient",
      "quality_coefficient",
      "technology_coefficient",
      "expert_coefficient",
      "development_coefficient",
      "call_count",
      "metering_amount",
    ]),
    technicalFields: technicalFields([
      "metering_id",
      "detail_id",
      "assessment_id",
      "parameter_snapshot_id",
      "output_snapshot_id",
      "checksum",
    ]),
  },
  {
    routePath: "/measure/utility",
    menuCode: "NAV_MEASURE_UTILITY",
    moduleCode: "UTIL",
    pageName: "贡献度与效用计算",
    mainTable: "contribution_record",
    tableFields: businessFields([
      "party_name",
      "valid_units",
      "usage_weight",
      "coverage_weight",
      "scarcity_weight",
      "contribution_score",
      "normalized_contribution",
      "quality_factor",
      "usage_factor",
      "scenario_factor",
      "utility_value",
    ]),
    technicalFields: technicalFields([
      "contribution_id",
      "utility_id",
      "utility_function_snapshot_id",
      "trace_id",
      "formula_text",
      "input_json",
      "output_json",
      "task_key",
    ]),
  },
  {
    routePath: "/allocation/md-dshap",
    menuCode: "NAV_ALLOC_MDS",
    moduleCode: "MDS",
    pageName: "MD-DShap 计算管理",
    mainTable: "md_dshap_task",
    tableFields: businessFields([
      "algorithm_mode",
      "participant_set",
      "task_set",
      "sample_rounds",
      "epsilon",
      "task_status",
      "party_name",
      "participant_weight",
      "normalized_weight",
      "marginal_contribution",
    ]),
    technicalFields: technicalFields([
      "task_id",
      "result_id",
      "trace_id",
      "algorithm_version",
      "seed",
      "baseline_weight",
      "weight_diff",
      "input_snapshot_json",
      "parameter_snapshot_json",
      "output_snapshot_json",
    ]),
  },
  {
    routePath: "/allocation/simulation",
    menuCode: "NAV_ALLOC_SIMULATION",
    moduleCode: "ALLOC",
    pageName: "收益分配模拟",
    mainTable: "allocation_scenario",
    tableFields: businessFields([
      "total_revenue",
      "priority_allocation_amount",
      "data_provider_revenue_pool",
      "allocation_mode",
      "party_name",
      "raw_weight",
      "normalized_weight",
      "pre_constraint_amount",
      "post_constraint_amount",
      "adjustment_reason",
      "scenario_status",
    ]),
    technicalFields: technicalFields([
      "allocation_id",
      "item_id",
      "result_id",
      "trace_id",
      "weight_task_id",
      "source_snapshot_id",
      "checksum",
      "rounding_note",
    ]),
  },
  {
    routePath: "/allocation/constraints",
    menuCode: "NAV_ALLOC_CONSTRAINT",
    moduleCode: "CONS",
    pageName: "合同约束管理",
    mainTable: "contract_constraint",
    tableFields: businessFields([
      "constraint_name",
      "party_name",
      "constraint_type",
      "value_type",
      "constraint_value",
      "priority",
      "status",
      "before_amount",
      "after_amount",
      "reason",
    ]),
    technicalFields: technicalFields([
      "constraint_id",
      "trace_id",
      "project_id",
      "allocation_id",
      "before_value",
      "after_value",
      "menu_code",
      "module_code",
    ]),
  },
  {
    routePath: "/reports",
    menuCode: "NAV_REPORT_EXPORT",
    moduleCode: "REP",
    pageName: "报告生成与导出",
    mainTable: "report_record",
    tableFields: businessFields([
      "report_type",
      "report_status",
      "file_name",
      "file_type",
      "field_scope",
      "generated_at",
      "created_by",
      "download_status",
      "p1_pdf_boundary",
    ]),
    technicalFields: technicalFields([
      "report_id",
      "file_id",
      "source_snapshot_id",
      "file_path",
      "checksum",
      "field_scope_json",
      "content_hash",
    ]),
  },
  {
    routePath: "/system/parameters",
    menuCode: "NAV_SYSTEM_PARAMETER",
    moduleCode: "PARAM",
    pageName: "参数配置",
    mainTable: "system_parameter",
    tableFields: businessFields([
      "parameter_group",
      "parameter_name",
      "parameter_value",
      "effective_status",
      "version_no",
      "updated_by",
      "updated_at",
      "risk_disclaimer_text",
    ]),
    technicalFields: technicalFields([
      "parameter_id",
      "parameter_version_id",
      "before_value",
      "after_value",
      "checksum",
      "menu_code",
      "module_code",
    ]),
  },
  {
    routePath: "/system/users",
    menuCode: "NAV_SYSTEM_USER",
    moduleCode: "USER",
    pageName: "用户与权限管理（P1）",
    mainTable: "user_account",
    tableFields: businessFields([
      "username",
      "display_name",
      "role_name",
      "menu_permission",
      "button_permission",
      "account_status",
      "p1_boundary",
    ]),
    technicalFields: technicalFields([
      "user_id",
      "role_id",
      "permission_id",
      "permission_code",
      "button_code",
      "password_reset_token",
    ]),
  },
  {
    routePath: "/system/audit",
    menuCode: "NAV_SYSTEM_AUDIT",
    moduleCode: "AUD",
    pageName: "审计日志管理",
    mainTable: "audit_log",
    tableFields: businessFields([
      "operation_type",
      "object_type",
      "operator_id",
      "module_code_display",
      "menu_code_display",
      "status",
      "failure_reason",
      "created_at",
      "report_type",
    ]),
    technicalFields: technicalFields([
      "log_id",
      "object_id",
      "before_value",
      "after_value",
      "input_snapshot_id",
      "parameter_snapshot_id",
      "output_snapshot_id",
      "report_id",
      "checksum",
    ]),
  },
];

export function getRouteFieldMapping(routePath: string) {
  return routeFieldMappings.find((mapping) => mapping.routePath === routePath);
}

export function getVisibleTableFields(mapping: RouteFieldMapping) {
  return mapping.tableFields.filter((field) => field.visibleInTable && !field.technical);
}

export function getFieldMapIntegrityReport() {
  const unlabeledBusinessFields = routeFieldMappings.flatMap((mapping) =>
    mapping.tableFields
      .filter((field) => field.label === field.key)
      .map((field) => `${mapping.routePath}:${field.key}`),
  );
  const visibleEngineeringFields = routeFieldMappings.flatMap((mapping) =>
    [...mapping.tableFields, ...mapping.technicalFields]
      .filter((field) => engineeringFieldKeys.has(field.key))
      .filter((field) => field.visibleInTable || !field.technical)
      .map((field) => `${mapping.routePath}:${field.key}`),
  );

  return {
    unlabeledBusinessFields,
    visibleEngineeringFields,
  };
}
